spring.application.name=univercity

# Включить подробные логи
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.boot.autoconfigure.thymeleaf=DEBUG
logging.level.org.thymeleaf=DEBUG

# Отключить кэш
spring.thymeleaf.cache=false
spring.thymeleaf.check-template-location=true

# Показать детали ошибок
server.error.include-stacktrace=always
server.error.include-message=always