spring.application.name=univercity

# Включить подробные логи
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.boot.autoconfigure.thymeleaf=DEBUG
logging.level.org.thymeleaf=DEBUG

# Отключить кэш
spring.thymeleaf.cache=false
spring.thymeleaf.check-template-location=true

# Показать детали ошибок
server.error.include-stacktrace=always
server.error.include-message=always

spring.main.allow-bean-definition-overriding=true

# PostgreSQL на порту 5433
spring.datasource.url=jdbc:postgresql://localhost:5433/university_schedule
spring.datasource.username=postgres
spring.datasource.password=MarcielleMarceline
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Отладка
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type=TRACE

spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
spring.jpa.hibernate.ddl-auto=update
